Test PHP OpenSSL against imaps

diff --git a/Dockerfiles/Dockerfile.jessie-arm64 b/Dockerfiles/Dockerfile.jessie-arm64
--- a/Dockerfiles/Dockerfile.jessie-arm64
+++ b/Dockerfiles/Dockerfile.jessie-arm64
@@ -5,7 +5,14 @@ MAINTAINER "cytopia" <cytopia@everythingcli.org>
 ENV PHP_VERSION=5.4.45
 ENV PHP_INI_DIR=/usr/local/etc/php
 
-ENV OPENSSL_VERSION=1.0.1t
+# As this is the Jessie Version already, we can skip custom OpenSSL installation
+
+# PHP 5.4 does not work with OpenSSL version from Debian Stretch (need to pick it from Jessie)
+# https://github.com/devilbox/docker-php-fpm-5.3/issues/7
+#
+# https://manpages.debian.org/jessie/openssl/openssl.1ssl.en.html
+# https://www.openssl.org/source/old/1.0.1/
+#ENV OPENSSL_VERSION=1.0.1t
 
 ENV PHP_BUILD_DEPS \
 	autoconf2.13 \
@@ -17,6 +24,7 @@ ENV PHP_BUILD_DEPS \
 	libreadline6-dev \
 	librecode-dev \
 	libsqlite3-dev \
+# libssl-dev/oldoldstable 1.0.1t-1
 	libssl-dev \
 	libxml2-dev
 
@@ -25,6 +33,7 @@ ENV PHP_RUNTIME_DEPS \
 	libpcre3 \
 	librecode0 \
 	libsqlite3-0 \
+# libssl1.0.0/oldoldstable,now 1.0.1t-1
 	libssl1.0.0 \
 	libxml2 \
 	xz-utils
@@ -81,51 +90,52 @@ RUN set -eux \
 		| awk -F'/' '{print $2}' \
 		| xargs -n1 apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys
 
+# As this is the Jessie Version already, we can skip custom OpenSSL installation
 
 ###
 ### Build OpenSSL
 ###
-RUN set -eux \
-# Install Dependencies
-	&& apt-get update \
-	&& apt-get install -y --no-install-recommends --no-install-suggests \
-		${BUILD_TOOLS} \
-	&& if [ "$(dpkg-architecture --query DEB_HOST_ARCH)" = "i386" ]; then \
-		apt-get install -y --no-install-recommends --no-install-suggests \
-			${BUILD_TOOLS_32}; \
-	fi \
-# Fetch OpenSSL
-	&& cd /tmp \
-	&& mkdir openssl \
-	&& update-ca-certificates \
-	&& curl -sS -k -L --fail "https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz" -o openssl.tar.gz \
-	&& curl -sS -k -L --fail "https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz.asc" -o openssl.tar.gz.asc \
-	&& tar -xzf openssl.tar.gz -C openssl --strip-components=1 \
-	&& cd /tmp/openssl \
-# Build OpenSSL
-	&& if [ "$(dpkg-architecture  --query DEB_HOST_ARCH)" = "i386" ]; then \
-		setarch i386 ./config -m32; \
-	else \
-		./config; \
-	fi \
-	&& make depend \
-	&& make -j"$(nproc)" \
-	&& make install \
-# Cleanup
-	&& rm -rf /tmp/* \
-# Ensure libs are linked to correct architecture directory
-	&& debMultiarch="$(dpkg-architecture --query DEB_BUILD_MULTIARCH)" \
-	&& mkdir -p "/usr/local/ssl/lib/${debMultiarch}" \
-	&& ln -s /usr/local/ssl/lib/* "/usr/local/ssl/lib/${debMultiarch}/" \
-# Remove Dependencies
-	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false \
-		${BUILD_TOOLS} \
-	&& if [ "$(dpkg-architecture --query DEB_HOST_ARCH)" = "i386" ]; then \
-		apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false \
-			${BUILD_TOOLS_32}; \
-	fi \
-	&& apt-get clean \
-	&& rm -rf /var/lib/apt/lists/*
+#RUN set -eux \
+## Install Dependencies
+#	&& apt-get update \
+#	&& apt-get install -y --no-install-recommends --no-install-suggests \
+#		${BUILD_TOOLS} \
+#	&& if [ "$(dpkg-architecture --query DEB_HOST_ARCH)" = "i386" ]; then \
+#		apt-get install -y --no-install-recommends --no-install-suggests \
+#			${BUILD_TOOLS_32}; \
+#	fi \
+## Fetch OpenSSL
+#	&& cd /tmp \
+#	&& mkdir openssl \
+#	&& update-ca-certificates \
+#	&& curl -sS -k -L --fail "https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz" -o openssl.tar.gz \
+#	&& curl -sS -k -L --fail "https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz.asc" -o openssl.tar.gz.asc \
+#	&& tar -xzf openssl.tar.gz -C openssl --strip-components=1 \
+#	&& cd /tmp/openssl \
+## Build OpenSSL
+#	&& if [ "$(dpkg-architecture  --query DEB_HOST_ARCH)" = "i386" ]; then \
+#		setarch i386 ./config -m32; \
+#	else \
+#		./config; \
+#	fi \
+#	&& make depend \
+#	&& make -j"$(nproc)" \
+#	&& make install \
+## Cleanup
+#	&& rm -rf /tmp/* \
+## Ensure libs are linked to correct architecture directory
+#	&& debMultiarch="$(dpkg-architecture --query DEB_BUILD_MULTIARCH)" \
+#	&& mkdir -p "/usr/local/ssl/lib/${debMultiarch}" \
+#	&& ln -s /usr/local/ssl/lib/* "/usr/local/ssl/lib/${debMultiarch}/" \
+## Remove Dependencies
+#	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false \
+#		${BUILD_TOOLS} \
+#	&& if [ "$(dpkg-architecture --query DEB_HOST_ARCH)" = "i386" ]; then \
+#		apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false \
+#			${BUILD_TOOLS_32}; \
+#	fi \
+#	&& apt-get clean \
+#	&& rm -rf /var/lib/apt/lists/*
 
 
 ###
@@ -203,7 +213,7 @@ RUN set -eux \
 		--with-sqlite3=/usr \
 		\
 		--with-curl \
-		--with-openssl=/usr/local/ssl \
+		--with-openssl \
 		--with-readline \
 		--with-recode \
 		--with-zlib \
